### ISSUE TITLE
Forms that are not hidden upon submission, show all conditionally hidden fields after submission

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms-conditional-logic#191]
If a form has the "HIDE SUCCESSFULLY COMPLETED FORM?" option turned off and has fields that are conditionally hidden, then upon submission all the conditionally hidden fields will show on the page. 

Replication Steps:
1. Create a form with a checkbox and textbox.
2. Set textbox to be hidden when the checkbox is checked. 
3. Turn off the "HIDE SUCCESSFULLY COMPLETED FORM?" option. 
4. Publish and add a submit button to the form. 
5. Preview the form. 
6. Do not check the checkbox and submit the form. You'll see that now the check box and textbox are both on the page.

**Comment by Much2tall** [comment]
https://github.com/wpninjas/ninja-forms-conditional-logic/pull/189
Resolved issue for every Field except the Submit Button.

**Comment by kstover** [comment]
Closing for now. If we get more reports related to the submit button, we can re-open.
