### ISSUE TITLE
condition met -> disable but still show field

### ISSUE THREAD

**Issue by hatsumatsu** [wpninjas/ninja-forms-conditional-logic#194]
Currently there is the option to hide fields based on the value of another field. To keep the layout intact is there a way to just disable the field instead of hiding it completely?

**Comment by Much2tall** [comment]
@hatsumatsu There is no out of the box way to do this.
Please note that this is not a support channel, GitHub is for confirmed issues with the product.
For further questions, please contact our support team (http://ninjaforms.com/contact/)
