### ISSUE TITLE
Single Checkbox Conditions Bug

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms-conditional-logic#197]
- Create two single checkbox and set the default value of the second 'Checked'.
- Creating this conditional logic: 'When checkbox 1 is checked, Do checkbox 2 change value unchecked, If This Condition is Not Met checkbox 2 change value checked'

Condition not firing as expected, which is for Checkbox 2 to be deselected upon checkbox 1 select. 
Checkbox conditions are set to zero.

**Comment by Much2tall** [comment]
Looks like the "Unchecked" option cannot be selected. Closing the drawer resets it to "Select One", implying that the value was never saved.
