### ISSUE TITLE
Conditionals that use the Equals option are not being triggered

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms-conditional-logic#210]
If a conditional is based off a calc value that is set to equal a specific number then the calc is not firing. 

Replication Steps, 
Create a form that has a single check box that has a calc value of 10 and a single line textbox. 
Create a calc that that has the check box in it. 
Create a condition that shows the single line text box if the calc equals 10.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/587691b0751e7f1100f1093a/event/5a6b9ccef3fbb80001e24e24
