### ISSUE TITLE
Fields that is used in a conditional statement is duplicated it breaks the condition

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms-conditional-logic#211]
If a field that is used in a conditional statement is duplicated then the conditional setting it was used on will be changed back to "Select One". 

Here is a screen cast showing the replication steps: 
https://drive.google.com/file/d/1zg_dByL6yK23zWwlL6fnP8eXkQFslzjo/view

**Comment by jkirker** [comment]
Any updates on this?
