### ISSUE TITLE
Single Checkbox fields are not triggering Conditional Logic changes

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms-conditional-logic#217]
"Single Checkbox" fields currently are not triggering Conditional Logic changes (hide/show) when checked or unchecked.

Checkbox List fields work normally.

**Comment by mjot** [comment]
Same Problem here.

**Comment by jmcelhaney** [comment]
I had the same issue with this user: https://wpninjas.kustomerapp.com/app/customers/5a81d5b0160c680001d7eceb/event/5a9d35da00434600017163d4
It appears that rolling back to 3.0.17 of Conditional Logic, saving the form, then upgrading to 3.0.18 again fixed there issue with Checkboxes.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5aa3bc7dc73eab00019aefd3/event/5aa3bc7d9cc4e80001a4456a

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5aa12666735ca90001d27a69/event/5aaa9a91d36e117eaa446bc8
