### ISSUE TITLE
Feature request: When adding a condition to show/hide a field, have a checkbox of fields so that you can mass show/hide

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms-conditional-logic#224]
A user requested the ability to mass show/hide fields via a checkbox instead of adding each field one at a time.

Once the checkbox of fields is selected, when you hit apply, it would create the conditional statements to show/hide the fields.

**Comment by wpnzach** [comment]
The use case for the majority of users would be better served with the current method, but field groupings or better interaction with multi part might be a viable solution for future released.
