### ISSUE TITLE
Change a value to another fields value

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms-conditional-logic#3]
See: http://wpninjas.com/members/support/ticket/issues-with-ninja-forms-mutli-part-layouts-styles/
The use case would be an order form where the user checks a box stating that their shipping address is the same as their billing address. Then all the fields can be pre-populated with the billing address field values the user has already submitted.
Maybe "Change Value" could offer an option to "Map to Another Field" or "Custom" or something similar.

**Comment by Much2tall** [comment]
Feature supported by current "develop" branch of Ninja Forms 3.
