### ISSUE TITLE
Required File Uploads fields being caught as Required when hidden by Conditional Logic

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms-conditional-logic#51]
Steps to reproduce:
Setup a File Uploads field as required then hide it with Conditional Logic. It will being caught as Required, even when hidden, when the form is submitted.

Form Export of the issue is attached.
### Environment

Home URL:                http://localhost:8888/wordpress
Site URL:                http://localhost:8888/wordpress
Ninja Forms Version:     2.9.33
WP Version:              4.4.2
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             5.6.10
MySQL Version:           5.5.42
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC
### Plugins

Installed Plugins:  
Ninja Forms - Conditional Logic by The WP Ninjas version 1.3.9
Ninja Forms - File Uploads by The WP Ninjas version 1.4.7
Ninja Forms by The WP Ninjas version 2.9.33

[fileupload---02-11-2016-.nff](https://files.zenhub.io/56bcc3a9f7471cd9688f07ab)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Much2tall** [comment]
Issue resolved in Ninja Forms 3.
