### ISSUE TITLE
Timed Submit does not work when there is Conditional Logic on the form

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms-conditional-logic#56]
Timed Submit does not work when there is Conditional Logic on the form
This happens with the 1.39 and 1.40 versions of Conditional Logic
Attached is an example form.
[Test---04-25-2016-.nff.zip](https://github.com/wpninjas/ninja-forms-conditional-logic/files/235233/Test---04-25-2016-.nff.zip)
### Environment

Home URL:                http://localhost/wordpress
Site URL:                http://localhost/wordpress
Ninja Forms Version:     2.9.42
WP Version:              4.5
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             5.6.10
MySQL Version:           5.5.42
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC
### Plugins

Installed Plugins:
                         Ninja Forms - Conditional Logic by The WP Ninjas version 1.4.0
                         Ninja Forms by The WP Ninjas version 2.9.42

**Comment by Much2tall** [comment]
Feature deprecated in Ninja Forms 3, rendering issue moot.
