### ISSUE TITLE
Date submitted conditional trigger causing fatal PHP error in 2.9.x

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms-conditional-logic#80]
If a form has an action with a date submitted conditional trigger. I'm seeing a PHP fatal error upon submission. I've detailed the error in the screenshot below. 

Screenshot: 
![screen shot 2016-08-15 at 3 50 20 pm](https://cloud.githubusercontent.com/assets/9393977/17677392/92593ec6-6300-11e6-834a-93250b72e4cd.png)

Replication Steps(in 2.9.x):
1. Create a new form. 
2. Add a first name field and submit field. 
3. Go to the "Emails and Actions" tab. 
4. Create a success message action. 
5. Add a date submitted on conditional and select today's date.
6. Preview and submit the form.

**Comment by Much2tall** [comment]
Feature not supported in Ninja Forms 3. So, related errors are a moot point.
